---
title: "A Sea-Saw Memory"
---

### A Sea-Saw Memory

impossible tired, marks along<br>
the winding trailing off, now called home<br>
the thin, precarious hairpin bend<br>
the two-steps back for one ahead<br>

the id hazard, a guess: all's not well<br>
the turbulent coast, waves on a rising swell<br>
as the sun in her smart histrionic display<br>
coaxes the dark and nightly coquets<br>

but from my reared view now<br>
I am still: that child,<br>
alone at the sea-<br>
saw: for miles,<br>
just me<br>

sat with a sickly sense of sweet<br>
that won't last: like ice cream<br>
melting too fast<br>

and a head:<br>
bounded by sallow fodder<br>
bound for fallow sod or<br>
sweat desert cones with powder tops<br>
a confection white, a salt lake shore<br>
and by Convection's might,<br>
nothing more<br>

but if Convention's right,<br>
I'll find Out soon<br>
(or else I'll get what is in store)<br>
and I'll pay the price<br>
for the ill I've done<br>
and then settle down<br>
for a while<br>

but this engine runs<br>
on hubris and speed<br>
and I take no wrong turns<br>
too carefully<br>

and this engine runs<br>
on ennui and greed<br>
and I don't change course<br>
graciously<br>

<br>
