---
title: "After Words"
---

### After Words

now I:<br>

&nbsp;&nbsp;tend still the tendrils<br>
&nbsp;&nbsp;that choke my bramble blooms<br>
&nbsp;&nbsp;with the contracted faith and fading strength<br>
&nbsp;&nbsp;of a farmer nearing noon<br>

&nbsp;&nbsp;even though these pumpkin petals<br>
&nbsp;&nbsp;never once offered one gourd<br>
&nbsp;&nbsp;or any sprig worth any more<br>
&nbsp;&nbsp;than a fleeting bud of hope<br>

&nbsp;&nbsp;but all whiter gifts grow just, to wither<br>
&nbsp;&nbsp;leaving: life's bittersweet surmise<br>
&nbsp;&nbsp;the sharpest edge is the pointless point<br>
&nbsp;&nbsp;that life's absurd playwright devised<br>

&nbsp;&nbsp;still in the moments, I feel whole<br>
&nbsp;&nbsp;(if the salience of parts subside<br>
&nbsp;&nbsp;&nbsp;&nbsp;to impart a peace of sense-like paradox<br>
&nbsp;&nbsp;&nbsp;&nbsp;of Christ harrowed yet divine)<br>

&nbsp;&nbsp;when by mistake or by design<br>
&nbsp;&nbsp;time's clink-clank engine comes to rest<br>
&nbsp;&nbsp;and my eyes drift above the Flatlands<br>
&nbsp;&nbsp;to a see rippled without crest<br>

<br>
