---
title: "Clocked Out"
---

### Clocked Out

once there was a time<br>
we made everything from stones<br>
but now it's all: We Do<br>
mistakes<br>

we take the whole<br>
and break it into its parts<br>
break it into a hole<br>
kind of mess:<br>
emptiness<br>

we are left<br>
with less than the whole<br>
less than the some<br>
remainder of it all<br>
left with more than enough<br>
reason enough<br>
to yearn<br>

while we know not<br>
what is<br>

the matter? some quota<br>
from some time gone<br>
from some Man-unkind who<br>
quoted "Production"<br>

suited for the Taylor<br>
or sew-it-seams<br>
for Man-aging without<br>
having been<br>

or for the clergy profit fellow<br>
who daily gives Appraise,<br>
the son of man, then asks again<br>
if any One can, save him from his syn-<br>
tactical corporate ideal<br>

to give:<br>
some way to feel?<br>

man as machine<br>
functional and clean<br>
held in high esteem<br>
but<br>

always, always<br>
searching<br>

for something more<br>
or something less<br>
some thing<br>

always, always<br>
searching<br>

since of-this-world<br>
had become<br>
mundane<br>

<br>
