---
title: "Collegetown, USA"
---

### Collegetown, USA

that's one more box of circuits<br>
for the free-cycle junkies<br>
who feed off the curb<br>
of end-days regret<br>

This city is a way-station;<br>
the people come<br>
only to leave<br>

like a screen saver<br>
that spawns fresh life<br>
from nothing, nowhere<br>
when we were too late to notice<br>
the first puncture in the landscape<br>
that swam downstream<br>

for awhile, there is<br>
new couches, new kitchens<br>
new coaches, new cushions<br>

until the wrist-flick moment:<br>
they all disappear<br>
and so will I<br>

It is a hard drive<br>
for anyone to take<br>
wound up in worn cables<br>
taut and intestate<br>
caught and decrepit<br>
like nana's mind,<br>

holding on to the last few shares<br>
of our joint venture<br>

a once ambitious young investor<br>
I denied the fundamentals<br>
that all markets<br>
contract<br>

this is the final rally<br>
of my dot-com boom<br>

I am sorry,<br>
but it is better that we know<br>
the mail flyer physics, who wrote:<br>
"Everything must go"<br>

<br>
