---
title: "Fiction"
---

### Screen Shot

##### [**The Finer Arts**](the-finer-arts.html)

##### [**Travel by Inner-state**](travel-by-inner-state.html)

##### [**Pharmakon**](pharmakon.html)

<br>

### Over Under

##### [**Jotnar Rising North**](jotnar-rising-north.html)

##### [**When the Weight Is Over**](when-the-weight-is-over.html)

##### [**Rinse and Retreat**](rinse-and-retreat.html)

##### [**Two Homes**](two-homes.html)

<br>

### Post-Space Postage

##### [**A Sea-Saw Memory**](a-sea-saw-memory.html)

##### [**Rorschachled and Bound**](rorschachled-and-bound.html)

##### [**Immolation Arch**](immolation-arch.html)

##### [**Clocked Out**](clocked-out.html)

<br>

### Unbounded

##### [**Held Back Cheers**](held-back-cheers.html)

##### [**An Old Erie Reminder**](an-old-erie-reminder.html)

##### [**Washed Assured**](washed-assured.html)

##### [**After Words**](after-words.html)

<br>

### Cardboard Counsel

##### [**As Sure As**](as-sure-as.html)

##### [**We Are All Seeking**](we-are-all-seeking.html)

##### [**The Ocean Is**](the-ocean-is.html)

<br>

### The Quiet Room

##### [**Settling**](settling.html)

##### [**Predication**](predication.html)

##### [**Resolute**](resolute.html)

##### [**Ingenuinity**](ingenuinity.html)

##### [**Jet-lagged**](jet-lagged.html)

##### [**Tinged**](tinged.html)

<br>

### The Life Drawer

##### [**For Alexander**](for-alexander.html)

##### [**Downcasted**](downcasted.html)

<br>

### Transitions

##### [**The Giving Tree (Foreword)**](the-giving-tree-foreword.html)

##### [**Transitions Pt. 2 & 3**](transitions-pt-2-and-3.html)

##### [**Transitions Pt. 4 & 8**](transitions-pt-4-and-8.html)

##### [**Transitions Pt. 5**](transitions-pt-5.html)

<br>
