---
title: "Held Back Cheers"
---

### Held Back Cheers

there's an intrusion detected<br>
a pollution prospected<br>
a seclusion projected<br>
by thoughts of belong<br>

so quick to the bottle and "AHH"<br>
the munition injected<br>
the confusion corrected<br>
the illusion perfected<br>
and finally clean:<br>

the glass, at last, the succulent mass<br>

to cover the pane<br>
that gapes the facade<br>
the unsheltered shapes<br>
between masonry parts<br>

where the cold draft blows<br>
until a cold drought flows<br>
downed, gargled, and gorged<br>
as the tongue tumbles and throws<br>

until tied up with letters<br>
mutant and transposed<br>
that like sorcery spell<br>
some other man's words<br>

and for what?<br>

the chance to spew matter<br>
noxious and scorn<br>
to lay retching and wretched<br>
on each Sabbath morn?<br>

on the job you proclaim,<br>
"I'm a practical man<br>
&nbsp;&nbsp;I live and let live<br>
&nbsp;&nbsp;&nbsp;&nbsp;and I do what I can."<br>
but is this really<br>
a tractable plan?<br>

to arrest your cognition<br>
for a minor infraction<br>
to solve for the "Why"<br>
with addiction subtraction?<br>

well, you can try<br>

to saturate the airways<br>
in subterfuge and collude<br>
with the agents who promise<br>
a prosperous deluge<br>
and cut through the wires<br>
that signal out smoke<br>
with chemical scissors<br>
along synaptic spokes<br>

but when the room stops its spin<br>
and the network goes live<br>
and the receiver tunes in<br>
to a crisp AM chime<br>
how will you mind?<br>

<br>
