---
title: "High on an End Note"
---

### High on an End Note

beneath the commerce chamber<br>
and the uncanny paint-peel front<br>
and the every way that man can make<br>
a meaning out of touch<br>

behind the compost culture<br>
and the chatterbox colloid crew<br>
and the radio jockeys reining<br>
another remix of the news<br>

beside the "journey is the destination"<br>
self-help guru hints<br>
and the counterfeit meditation<br>
and imposter prophet<br>
prints<br>

beyond the tempest of temptation<br>
setting sail to a cardinal sin<br>
and the rot of the spoiled victor<br>
and the daily pyrrhic<br>
win<br>

there is a residue<br>
that I wish could say<br>
in a simple "A is for Apple" kind of way<br>
to make you understand:<br>

the point of this infliction<br>
the problem of the crux<br>
the crisis at hand<br>

to make you see:<br>
what the mystics and the mountaineers<br>
were never supposed to suppose<br>

that above all else, I remember what is true<br>
all the loneliness in knowing anyone<br>
all the boredom in knowing anything<br>

and life's one best-kept secret:<br>
that the peak of disappointment<br>
is to reach the summit<br>

<br>
