---
title: "No Reception"
---

### No Reception

it was the last coherent summer<br>
the search engines had learned to dream<br>
there was a comfort in the old sense of the word<br>
and the people still believed in goodness' sake<br>

when I saw you again<br>
I had just gotten married<br>
and you were out of jail<br>
for stealing a dog from a witch<br>

I don't think you believed me<br>
when I said I knew about the black magic<br>
that I had seen the eternal serpent machine<br>
spin its Fibonocci spirals<br>
from behind a thin veil<br>

the sight of your broken dream is fixed now in my mind<br>
you stood there, a still life of dead game<br>
strung out like a hare caught in a pin<br>
plucked like a pheasant on display<br>

there is a civil war inside all of us<br>
between an oppressor and the oppressed<br>
both blame the self and the other<br>
for their disunited state<br>

the burden of responsibility<br>
is to be expected<br>

but when armistice comes<br>
will you forgive the practical man<br>
who had known the horrors of Santo Domingo<br>
who had wept for the heroes cut out on a limb<br>
who withdrew his hand?<br>

<br>
