---
title: "Pharmakon"
---

### Pharmakon

age 11, reading e.e. cummings<br>

I ask the teacher:<br>
Why can e. defy the rule of grammar?<br>
"Creative license", she said.<br>

Wow! Even as a kid I understood<br>
that kind of power<br>
to rebel against the Capitol<br>
to punctuate any order<br>
to choose, full stop<br>

I only wanted to know:<br>
How could I get one too?<br>

in the word world of children<br>
language is everything<br>
but all the pallets of grey<br>
take years to unpack<br>

like how<br>
an incision is a fresh wound<br>
painful and bled in the same vein<br>
and a smile is mostly incisors<br>

I used to think the home-less were house-less<br>
not slept away in a second story<br>
where the boarded up windows keep<br>
the idea of people out<br>

tucked beneath worn blankets<br>
and torn sleeping bags<br>
and more discarded<br>
wrappers<br>

a general man told me,<br>
"when you wage war,<br>
&nbsp;&nbsp;you must expect some<br>
&nbsp;&nbsp;collateral damage"<br>

but never spoke about how<br>
through the gaps in the gable,<br>
like a lapse in a fable,<br>
the unseen still see<br>

the same snow fill, up<br>
the old spruce hill<br>
where professors obstruct<br>
a pure structural view<br>

"in the word world of children<br>
&nbsp;&nbsp;language is everything"<br>

it is so obvious to those<br>
who eat the food that mothers cook<br>
and never once, either<br>
foolish or stubborn<br>
tasted poison<br>

<br>
