---
title: "Presentations"
---

### Presentations

Erb I, **Quinn T**, Lovell D, & Notredame C. June 2017. Differential proportionality: an alternative to differential gene expression not requiring sample normalization. Poster presented at CoDaWork in Tuscany, Italy.

**Quinn T**, Richardson M, Lovell D, & Crowley T. February 2017. propr: An R Package for Identifying Proportionally Expressed Genes using Compositional Data Analysis. Poster presented at Lorne Genome Conference in Lorne, Australia.

**Quinn T**, Richardson M, Lovell D, & Crowley T. October 2016. propr: An R Package for Identifying Proportionally Expressed Genes using Compositional Data Analysis. Poster presented at Australasian Genomic Technologies Association in Auckland, New Zealand.

**Quinn TP**, Tylee DS, Bichindaritz IB, & Glatt SJ. April 2016. Constructing Generalizable Classifiers for the Classification of Complex Biological Disorders. Poster presented at SUNY Upstate Medical University Student Research Day in Syracuse, New York.

Tylee DS, Hess JL, **Quinn TP**, Barve R, & Glatt SJ. April 2016. Transcriptome-wide mega-analysis of blood-based microarray data comparing individuals with autism and typically developing subjects. Poster presented at SUNY Upstate Medical University Student Research Day in Syracuse, New York.

**Quinn TP**, Tylee DS, Bichindaritz IB, & Glatt SJ. March 2016. Constructing Generalizable Classifiers for the Classification of Complex Biological Disorders. Poster presented at The NYAS Annual Machine Learning Symposium in New York, New York.

Tylee DS, Hess JL, **Quinn TP**, Barve R, & Glatt SJ. October 2015. Transcriptome-wide mega-analysis of blood-based microarray data comparing individuals with autism and typically developing subjects. Poster presented at World Congress of Psychiatric Genetics in Toronto, Canada.

Tylee DS, **Quinn TP**, & Glatt SJ. June 2015. Improving SVM classifiers using resampling and aggregation: A blood-based transcriptomic study of children with autism. Poster presented at Cold Spring Harbor Workshop on Autism Spectrum Disorders in Cold Spring Harbor, New York.

Tylee DS, **Quinn TP**, & Glatt SJ. October 2014. Improving SVM classifiers using resampling and aggregation: A blood-based transcriptomic study of children with autism. Poster presented at World Congress of Psychiatric Genetics in Copenhagen, Denmark.

Glatt SJ, **Quinn TP**, & Tylee DS. October 2014. Building better classifiers: optimizing models of heterogeneous neuropsychiatric disorders derived from high-dimensional data. Poster presented at World Congress of Psychiatric Genetics in Copenhagen, Denmark.

**Quinn TP**, Hess JL, & Glatt SJ. April 2014. In silico discovery of transcription factor-binding motifs disrupted by single nucleotide polymorphisms associated with multiple psychiatric disorders. Poster presented at SUNY Upstate Medical University Student Research Day in Syracuse, New York.

**Quinn TP**, Minicozzi M, & Mass S. April 2011. Biometrics of metamorphosed and neotenic axolotls. Poster presented at SUNY New Paltz Student Research Symposium in New Paltz, New York.

**Quinn TP**. September 2010. New chiral shift reagents. Lecture presented through the SUNY New Paltz Student Undergraduate Research Experience (SURE) Program in New Paltz, New York.

**Quinn TP** & Folmer-Andersen J. April 2010. New macrocycles as chiral shift reagents. Poster presented at SUNY New Paltz Student Research Symposium in New Paltz, New York.

**Quinn TP** & Folmer-Andersen J. April 2010. New macrocycles as chiral shift reagents. Poster presented at Bard University in Red Hook, New York.

**Quinn TP**. July 2009. Anthropogenic inputs in the Hudson River estuary. Lecture presented through the SUNY Purchase Bridges to Baccalaureate Program in Harrison, New York.

**Quinn TP**. July 2009. The Role of Horizontal and Vertical Learning in Chimpanzee Populations. Lecture presented at Beacon Conference for Student Scholars at Two-Year Colleges in Takoma Park, Maryland.

<br>
