---
title: "Second-hand Derivative"
---

### Second-hand Derivative

I don't miss those days<br>
but some nights, when I am laid out flat<br>
under the weather, and covered<br>

by a thin sheet of sifted clouds<br>
and the moonlight slips through<br>
the señorita curtains<br>
almost unnoticed:<br>

I think back to the time when<br>
I'd think back to the time<br>

when the summer meant no less<br>
than a solstice spent<br>
running down the run-down block<br>
and up again, from the top: the third act<br>
of our Cowboy and Indian play<br>
chock-full of tricks and treaties<br>
until the Spaghetti Western sun<br>
would send us all home<br>
as redskins<br>

in an epoch of reverie<br>
the mistakes are always obvious<br>
like the specs on the blue-sky blue-print<br>
of the hippie architect<br>
pitching us another<br>
over-budget utopia<br>

yes, there are parts of life<br>
I too prefer to forget<br>
but then again:<br>

I think back to the time when<br>
I'd think back to the time<br>

when I was convinced<br>
of the triumph of the demos<br>
of the primacy of tomorrow<br>
of the fallacy of fate<br>

I don't miss those days<br>
but some nights, when I am laid out flat<br>
under the weather, and covered<br>

I get tangled in a second-order sorrow<br>
caught in the longing for a longing<br>
in the loss of a loss<br>

<br>
