---
title: "The Finer Arts"
---

### The Finer Arts

the woman with my ring, she rang<br>
just to say,<br>
"Goodnight.<br>
&nbsp;&nbsp;I know you're working hard these days.<br>
&nbsp;&nbsp;Everything will be alright."<br>

silencing the phone insight<br>
it's so easy now to lie<br>
when the face I face is reflective screen<br>
and I key in my reply<br>

and so where were we? oh yeah,<br>
that's right: drowning in this dive<br>
sat on a lackluster lacquer bench<br>
where no friendly eyes dare pry<br>

beneath some halos of halogen<br>
we speak of ancient psalms<br>
and disemboweled mammalian forms<br>
you know just how to turn me on<br>

and in dim light, it's so clear<br>
how stranger is the problem where<br>
we both want the same thing<br>
we both want to fuck<br>
it all up:<br>

every picture perfect memory<br>
the holidays along Atlantic coasts<br>
the anniversary in Old San Juan<br>
arguing who loves who the most<br>

they're all picture perfect memories<br>
but I need something more<br>
a photograph to hold onto<br>
like a God damned whore<br>

<br>
