---
title: "The Ideal Problem"
---

### The Ideal Problem

her words fell on the paper<br>
like racoon garbage driven out onto the streets<br>
separate now from its insecure<br>
and overflown receptacle<br>

there's a kind of freedom there<br>
in the fetid way that a spoiled rag<br>
festers on top of a bitumen strip<br>
folded in on itself like a dead origami rose,<br>
sat with satin stains of beige and cherry swirls,<br>
no longer conscribed to the over-arching narrative<br>
no longer eligible for reprieve<br>
free: to be taken;<br>
out of context<br>

free to be; a reminder<br>
that somebody needs to clean up<br>
this mess<br>

in any utopia, there is<br>
a farm hand who would rather be a dreadnought<br>
a prison guard who enjoys the night shift<br>
a grave digger who works weekends<br>

tell me<br>
do you know when enough is a lot?<br>
do you know how a bleeding heart clots?<br>

see, the sad truth is<br>
every writer needs an editor<br>
someone who can scrub cat piss<br>
out of a blanket statement<br>
someone who knows better<br>
than to say what<br>
they mean<br>

a poem is an olive<br>
that must be soaked in a bath of lye<br>
to be cured from the natural<br>
taste of its creator<br>

<br>
