---
title: "The Giving Tree (Foreword)"
---

### The Giving Tree (Foreword)

it was a warm day in October<br>
when our feet finally took hold<br>
to the same earth that cradles<br>
every beast in this world<br>

when before night we had devised<br>
how to make paper from skin<br>
and we took care as we took turns<br>
carving our initials in<br>

and although we both knew too well<br>
we were only built of flesh parts<br>
we dared to write "Forever"<br>
beneath the names and the heart<br>

but the lichen testified before us<br>
that every dream can and will<br>
reach great heights if dreamt asleep<br>
beside the Falls of the Neverkille<br>

then you took the time to pause the day<br>
to promise me you always would<br>
meet me here with shelter<br>
if the winds of pain passed through<br>

and I knew you hadn't much<br>
lining the pockets of your green dress<br>
still you told me in no ambiguous terms<br>
I'd always have the better half<br>

but the words that would burgeon<br>
from the gardens of your tongue<br>
was all it ever took to make me want<br>
to taste the air with my lungs<br>

now at times I wonder if the crab apples<br>
we ate were maybe just starch<br>
but they were ours and they were so sweet<br>
when we'd watch the crayfish march<br>

<br>
