---
title: "When the Weight Is Over"
---

### When the Weight Is Over

recovered from my winning spree<br>
heeled back to the ridge of brimming scree<br>
tracing trepid steps, bracing dreaded depths<br>
I forgot how long it's been<br>
since I had wanted to start again<br>
since I had wanted it all to end<br>
since I couldn't remember when<br>

it was a need-to-know: just how landslips flow<br>
when the weight is over<br>

now it's all aboard the always bored<br>
the man of the hour's one of twenty-four<br>
enough to occupy, until the next time<br>
but there is comfort in the coach<br>
that keeps you right on track<br>
that keeps you trained to task<br>
that holds you to the fact<br>

it was a need-to-know: just how gaskets blow<br>
when the weight is over<br>

and like a city beat boombox<br>
and like a city street buttagots<br>
a rumpus is harmony to some<br>

today, holly bloomed in city square<br>
as the suits volleyed gloomy, pity stares<br>
on a writer's block, words get chopped<br>
to form a death sentence, I breathe<br>
as if all I needed was inspiration<br>
as if all I had was not expiration<br>
but if I've ever learned one lesson<br>

it was a need-to-know: just how branches bow<br>
when the weight is over<br>

<br>
